name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://npm.pkg.github.com/
          scope: '@segmentstream'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true

      - name: publish
        run: npm publish --tag `git rev-parse --short HEAD`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
