// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1SecretKeySelector,
} from './';

/**
 * ArtifactoryAuth describes the secret selectors required for authenticating to artifactory
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ArtifactoryAuth
 */
export interface IoArgoprojWorkflowV1alpha1ArtifactoryAuth {
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactoryAuth
     */
    passwordSecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactoryAuth
     */
    usernameSecret?: IoK8sApiCoreV1SecretKeySelector;
}
