// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1ConfigMapKeySelector,
    IoK8sApiCoreV1SecretKeySelector,
} from './';

/**
 * HDFSKrbConfig is auth configurations for Kerberos
 * @export
 * @interface IoArgoprojWorkflowV1alpha1HDFSKrbConfig
 */
export interface IoArgoprojWorkflowV1alpha1HDFSKrbConfig {
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbCCacheSecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * @type {IoK8sApiCoreV1ConfigMapKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbConfigConfigMap?: IoK8sApiCoreV1ConfigMapKeySelector;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbKeytabSecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbRealm?: string;
    /**
     * KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbServicePrincipalName?: string;
    /**
     * KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1HDFSKrbConfig
     */
    krbUsername?: string;
}
