// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RetryStrategy provides controls on how to retry a workflow step
 * @export
 * @interface IoArgoprojWorkflowV1alpha1RetryStrategy
 */
export interface IoArgoprojWorkflowV1alpha1RetryStrategy {
    /**
     * Limit is the maximum number of attempts when retrying a container
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1RetryStrategy
     */
    limit?: number;
}
