// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Artifact,
    IoArgoprojWorkflowV1alpha1Parameter,
} from './';

/**
 * Inputs are the mechanism for passing parameters, artifacts, volumes from one template to another
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Inputs
 */
export interface IoArgoprojWorkflowV1alpha1Inputs {
    /**
     * Artifact are a list of artifacts passed as inputs
     * @type {Array<IoArgoprojWorkflowV1alpha1Artifact>}
     * @memberof IoArgoprojWorkflowV1alpha1Inputs
     */
    artifacts?: Array<IoArgoprojWorkflowV1alpha1Artifact>;
    /**
     * Parameters are a list of parameters passed as inputs
     * @type {Array<IoArgoprojWorkflowV1alpha1Parameter>}
     * @memberof IoArgoprojWorkflowV1alpha1Inputs
     */
    parameters?: Array<IoArgoprojWorkflowV1alpha1Parameter>;
}
