// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ArchiveStrategy describes how to archive files/directory when saving artifacts
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ArchiveStrategy
 */
export interface IoArgoprojWorkflowV1alpha1ArchiveStrategy {
    /**
     * NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.
     * @type {object}
     * @memberof IoArgoprojWorkflowV1alpha1ArchiveStrategy
     */
    none?: object;
    /**
     * TarStrategy will tar and gzip the file or directory when saving
     * @type {object}
     * @memberof IoArgoprojWorkflowV1alpha1ArchiveStrategy
     */
    tar?: object;
}
