// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Arguments,
    IoArgoprojWorkflowV1alpha1ContinueOn,
    IoArgoprojWorkflowV1alpha1Sequence,
} from './';

/**
 * DAGTask represents a node in the graph during DAG execution
 * @export
 * @interface IoArgoprojWorkflowV1alpha1DAGTask
 */
export interface IoArgoprojWorkflowV1alpha1DAGTask {
    /**
     * @type {IoArgoprojWorkflowV1alpha1Arguments}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    arguments?: IoArgoprojWorkflowV1alpha1Arguments;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ContinueOn}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    continueOn?: IoArgoprojWorkflowV1alpha1ContinueOn;
    /**
     * Dependencies are name of other targets which this depends on
     * @type {Array<string>}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    dependencies?: Array<string>;
    /**
     * Name is the name of the target
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    name: string;
    /**
     * Name of template to execute
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    template: string;
    /**
     * When is an expression in which the task should conditionally execute
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    when?: string;
    /**
     * WithItems expands a task into multiple parallel tasks from the items in the list
     * @type {Array<string>}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    withItems?: Array<string>;
    /**
     * WithParam expands a task into multiple parallel tasks from the value in the parameter, which is expected to be a JSON list.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    withParam?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1Sequence}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTask
     */
    withSequence?: IoArgoprojWorkflowV1alpha1Sequence;
}
