// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1SecretKeySelector,
} from './';

/**
 * ArtifactoryArtifact is the location of an artifactory artifact
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
 */
export interface IoArgoprojWorkflowV1alpha1ArtifactoryArtifact {
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
     */
    passwordSecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * URL of the artifact
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
     */
    url: string;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactoryArtifact
     */
    usernameSecret?: IoK8sApiCoreV1SecretKeySelector;
}
