// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ResourceTemplate is a template subtype to manipulate kubernetes resources
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ResourceTemplate
 */
export interface IoArgoprojWorkflowV1alpha1ResourceTemplate {
    /**
     * Action is the action to perform to the resource. Must be one of: get, create, apply, delete, replace
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ResourceTemplate
     */
    action: string;
    /**
     * FailureCondition is a label selector expression which describes the conditions of the k8s resource in which the step was considered failed
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ResourceTemplate
     */
    failureCondition?: string;
    /**
     * Manifest contains the kubernetes manifest
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ResourceTemplate
     */
    manifest: string;
    /**
     * MergeStrategy is the strategy used to merge a patch. It defaults to \"strategic\" Must be one of: strategic, merge, json
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ResourceTemplate
     */
    mergeStrategy?: string;
    /**
     * SuccessCondition is a label selector expression which describes the conditions of the k8s resource in which it is acceptable to proceed to the following step
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ResourceTemplate
     */
    successCondition?: string;
}
