// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * HTTPArtifact allows an file served on HTTP to be placed as an input artifact in a container
 * @export
 * @interface IoArgoprojWorkflowV1alpha1HTTPArtifact
 */
export interface IoArgoprojWorkflowV1alpha1HTTPArtifact {
    /**
     * URL of the artifact
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1HTTPArtifact
     */
    url: string;
}
