// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ValueFrom describes a location in which to obtain the value to a parameter
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ValueFrom
 */
export interface IoArgoprojWorkflowV1alpha1ValueFrom {
    /**
     * JQFilter expression against the resource object in resource templates
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ValueFrom
     */
    jqFilter?: string;
    /**
     * JSONPath of a resource to retrieve an output parameter value from in resource templates
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ValueFrom
     */
    jsonPath?: string;
    /**
     * Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. \'{{steps.mystep.outputs.myparam}}\')
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ValueFrom
     */
    parameter?: string;
    /**
     * Path in the container to retrieve an output parameter value from in container templates
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1ValueFrom
     */
    path?: string;
}
