// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1WorkflowSpec,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * Workflow is the definition of a workflow resource
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Workflow
 */
export interface IoArgoprojWorkflowV1alpha1Workflow {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Workflow
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Workflow
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoArgoprojWorkflowV1alpha1Workflow
     */
    metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoArgoprojWorkflowV1alpha1WorkflowSpec}
     * @memberof IoArgoprojWorkflowV1alpha1Workflow
     */
    spec: IoArgoprojWorkflowV1alpha1WorkflowSpec;
    /**
     * @type {IoArgoprojWorkflowV1alpha1WorkflowStatus}
     * @memberof IoArgoprojWorkflowV1alpha1Workflow
     */
    status: any;
}
