// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1DAGTask,
} from './';

/**
 * DAGTemplate is a template subtype for directed acyclic graph templates
 * @export
 * @interface IoArgoprojWorkflowV1alpha1DAGTemplate
 */
export interface IoArgoprojWorkflowV1alpha1DAGTemplate {
    /**
     * Target are one or more names of targets to execute in a DAG
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTemplate
     */
    target?: string;
    /**
     * Tasks are a list of DAG tasks
     * @type {Array<IoArgoprojWorkflowV1alpha1DAGTask>}
     * @memberof IoArgoprojWorkflowV1alpha1DAGTemplate
     */
    tasks: Array<IoArgoprojWorkflowV1alpha1DAGTask>;
}
