// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Workflow,
    IoK8sApimachineryPkgApisMetaV1ListMeta,
} from './';

/**
 * WorkflowList is list of Workflow resources
 * @export
 * @interface IoArgoprojWorkflowV1alpha1WorkflowList
 */
export interface IoArgoprojWorkflowV1alpha1WorkflowList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowList
     */
    apiVersion?: string;
    /**
     * @type {Array<IoArgoprojWorkflowV1alpha1Workflow>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowList
     */
    items: Array<IoArgoprojWorkflowV1alpha1Workflow>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowList
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowList
     */
    metadata: IoK8sApimachineryPkgApisMetaV1ListMeta;
}
