// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Arguments,
    IoArgoprojWorkflowV1alpha1Template,
    IoK8sApiCoreV1Affinity,
    IoK8sApiCoreV1LocalObjectReference,
    IoK8sApiCoreV1PersistentVolumeClaim,
    IoK8sApiCoreV1PodDNSConfig,
    IoK8sApiCoreV1Toleration,
    IoK8sApiCoreV1Volume,
} from './';

/**
 * WorkflowSpec is the specification of a Workflow.
 * @export
 * @interface IoArgoprojWorkflowV1alpha1WorkflowSpec
 */
export interface IoArgoprojWorkflowV1alpha1WorkflowSpec {
    /**
     * Optional duration in seconds relative to the workflow start time which the workflow is allowed to run before the controller terminates the workflow. A value of zero is used to terminate a Running workflow
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    activeDeadlineSeconds?: number;
    /**
     * @type {IoK8sApiCoreV1Affinity}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    affinity?: IoK8sApiCoreV1Affinity;
    /**
     * @type {IoArgoprojWorkflowV1alpha1Arguments}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    arguments?: IoArgoprojWorkflowV1alpha1Arguments;
    /**
     * @type {IoK8sApiCoreV1PodDNSConfig}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    dnsConfig?: IoK8sApiCoreV1PodDNSConfig;
    /**
     * Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are \'ClusterFirstWithHostNet\', \'ClusterFirst\', \'Default\' or \'None\'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to \'ClusterFirstWithHostNet\'.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    dnsPolicy?: string;
    /**
     * Entrypoint is a template reference to the starting point of the workflow
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    entrypoint: string;
    /**
     * Host networking requested for this workflow pod. Default to false.
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    hostNetwork?: boolean;
    /**
     * ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount. ImagePullSecrets are distinct from Secrets because Secrets can be mounted in the pod, but ImagePullSecrets are only accessed by the kubelet. More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
     * @type {Array<IoK8sApiCoreV1LocalObjectReference>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    imagePullSecrets?: Array<IoK8sApiCoreV1LocalObjectReference>;
    /**
     * NodeSelector is a selector which will result in all pods of the workflow to be scheduled on the selected node(s). This is able to be overridden by a nodeSelector specified in the template.
     * @type {{ [key: string]: string; }}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    nodeSelector?: { [key: string]: string; };
    /**
     * OnExit is a template reference which is invoked at the end of the workflow, irrespective of the success, failure, or error of the primary workflow.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    onExit?: string;
    /**
     * Parallelism limits the max total parallel pods that can execute at the same time in a workflow
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    parallelism?: number;
    /**
     * Priority to apply to workflow pods.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    podPriority?: number;
    /**
     * PriorityClassName to apply to workflow pods.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    podPriorityClassName?: string;
    /**
     * Priority is used if controller is configured to process limited number of workflows in parallel. Workflows with higher priority are processed first.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    priority?: number;
    /**
     * Set scheduler name for all pods. Will be overridden if container/script template\'s scheduler name is set. Default scheduler will be used if neither specified.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    schedulerName?: string;
    /**
     * ServiceAccountName is the name of the ServiceAccount to run all pods of the workflow as.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    serviceAccountName?: string;
    /**
     * Suspend will suspend the workflow and prevent execution of any future steps in the workflow
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    suspend?: boolean;
    /**
     * Templates is a list of workflow templates used in a workflow
     * @type {Array<IoArgoprojWorkflowV1alpha1Template>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    templates: Array<IoArgoprojWorkflowV1alpha1Template>;
    /**
     * Tolerations to apply to workflow pods.
     * @type {Array<IoK8sApiCoreV1Toleration>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    tolerations?: Array<IoK8sApiCoreV1Toleration>;
    /**
     * TTLSecondsAfterFinished limits the lifetime of a Workflow that has finished execution (Succeeded, Failed, Error). If this field is set, once the Workflow finishes, it will be deleted after ttlSecondsAfterFinished expires. If this field is unset, ttlSecondsAfterFinished will not expire. If this field is set to zero, ttlSecondsAfterFinished expires immediately after the Workflow finishes.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    ttlSecondsAfterFinished?: number;
    /**
     * VolumeClaimTemplates is a list of claims that containers are allowed to reference. The Workflow controller will create the claims at the beginning of the workflow and delete the claims upon completion of the workflow
     * @type {Array<IoK8sApiCoreV1PersistentVolumeClaim>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    volumeClaimTemplates?: Array<IoK8sApiCoreV1PersistentVolumeClaim>;
    /**
     * Volumes is a list of volumes that can be mounted by containers in a workflow.
     * @type {Array<IoK8sApiCoreV1Volume>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowSpec
     */
    volumes?: Array<IoK8sApiCoreV1Volume>;
}
