// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1ArchiveStrategy,
    IoArgoprojWorkflowV1alpha1ArtifactoryArtifact,
    IoArgoprojWorkflowV1alpha1GitArtifact,
    IoArgoprojWorkflowV1alpha1HDFSArtifact,
    IoArgoprojWorkflowV1alpha1HTTPArtifact,
    IoArgoprojWorkflowV1alpha1RawArtifact,
    IoArgoprojWorkflowV1alpha1S3Artifact,
} from './';

/**
 * Artifact indicates an artifact to place at a specified path
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Artifact
 */
export interface IoArgoprojWorkflowV1alpha1Artifact {
    /**
     * @type {IoArgoprojWorkflowV1alpha1ArchiveStrategy}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    archive?: IoArgoprojWorkflowV1alpha1ArchiveStrategy;
    /**
     * ArchiveLogs indicates if the container logs should be archived
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    archiveLogs?: boolean;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ArtifactoryArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    artifactory?: IoArgoprojWorkflowV1alpha1ArtifactoryArtifact;
    /**
     * From allows an artifact to reference an artifact from a previous step
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    from?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1GitArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    git?: IoArgoprojWorkflowV1alpha1GitArtifact;
    /**
     * GlobalName exports an output artifact to the global scope, making it available as \'{{workflow.outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    globalName?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1HDFSArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    hdfs?: IoArgoprojWorkflowV1alpha1HDFSArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1HTTPArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    http?: IoArgoprojWorkflowV1alpha1HTTPArtifact;
    /**
     * mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    mode?: number;
    /**
     * name of the artifact. must be unique within a template\'s inputs/outputs.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    name: string;
    /**
     * Make Artifacts optional, if Artifacts doesn\'t generate or exist
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    optional?: boolean;
    /**
     * Path is the container path to the artifact
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    path?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1RawArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    raw?: IoArgoprojWorkflowV1alpha1RawArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1S3Artifact}
     * @memberof IoArgoprojWorkflowV1alpha1Artifact
     */
    s3?: IoArgoprojWorkflowV1alpha1S3Artifact;
}
