// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Artifact,
    IoArgoprojWorkflowV1alpha1Parameter,
} from './';

/**
 * Arguments to a template
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Arguments
 */
export interface IoArgoprojWorkflowV1alpha1Arguments {
    /**
     * Artifacts is the list of artifacts to pass to the template or workflow
     * @type {Array<IoArgoprojWorkflowV1alpha1Artifact>}
     * @memberof IoArgoprojWorkflowV1alpha1Arguments
     */
    artifacts?: Array<IoArgoprojWorkflowV1alpha1Artifact>;
    /**
     * Parameters is the list of parameters to pass to the template or workflow
     * @type {Array<IoArgoprojWorkflowV1alpha1Parameter>}
     * @memberof IoArgoprojWorkflowV1alpha1Arguments
     */
    parameters?: Array<IoArgoprojWorkflowV1alpha1Parameter>;
}
