// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RawArtifact allows raw string content to be placed as an artifact in a container
 * @export
 * @interface IoArgoprojWorkflowV1alpha1RawArtifact
 */
export interface IoArgoprojWorkflowV1alpha1RawArtifact {
    /**
     * Data is the string contents of the artifact
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1RawArtifact
     */
    data: string;
}
