// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1SecretKeySelector,
} from './';

/**
 * S3Bucket contains the access information required for interfacing with an S3 bucket
 * @export
 * @interface IoArgoprojWorkflowV1alpha1S3Bucket
 */
export interface IoArgoprojWorkflowV1alpha1S3Bucket {
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    accessKeySecret: IoK8sApiCoreV1SecretKeySelector;
    /**
     * Bucket is the name of the bucket
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    bucket: string;
    /**
     * Endpoint is the hostname of the bucket endpoint
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    endpoint: string;
    /**
     * Insecure will connect to the service with TLS
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    insecure?: boolean;
    /**
     * Region contains the optional bucket region
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    region?: string;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1S3Bucket
     */
    secretKeySecret: IoK8sApiCoreV1SecretKeySelector;
}
