// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Arguments,
    IoArgoprojWorkflowV1alpha1ContinueOn,
    IoArgoprojWorkflowV1alpha1Sequence,
} from './';

/**
 * WorkflowStep is a reference to a template to execute in a series of step
 * @export
 * @interface IoArgoprojWorkflowV1alpha1WorkflowStep
 */
export interface IoArgoprojWorkflowV1alpha1WorkflowStep {
    /**
     * @type {IoArgoprojWorkflowV1alpha1Arguments}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    arguments?: IoArgoprojWorkflowV1alpha1Arguments;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ContinueOn}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    continueOn?: IoArgoprojWorkflowV1alpha1ContinueOn;
    /**
     * Name of the step
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    name?: string;
    /**
     * Template is a reference to the template to execute as the step
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    template?: string;
    /**
     * When is an expression in which the step should conditionally execute
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    when?: string;
    /**
     * WithItems expands a step into multiple parallel steps from the items in the list
     * @type {Array<string>}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    withItems?: Array<string>;
    /**
     * WithParam expands a step into multiple parallel steps from the value in the parameter, which is expected to be a JSON list.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    withParam?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1Sequence}
     * @memberof IoArgoprojWorkflowV1alpha1WorkflowStep
     */
    withSequence?: IoArgoprojWorkflowV1alpha1Sequence;
}
