// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1Artifact,
    IoArgoprojWorkflowV1alpha1Parameter,
} from './';

/**
 * Outputs hold parameters, artifacts, and results from a step
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Outputs
 */
export interface IoArgoprojWorkflowV1alpha1Outputs {
    /**
     * Artifacts holds the list of output artifacts produced by a step
     * @type {Array<IoArgoprojWorkflowV1alpha1Artifact>}
     * @memberof IoArgoprojWorkflowV1alpha1Outputs
     */
    artifacts?: Array<IoArgoprojWorkflowV1alpha1Artifact>;
    /**
     * Parameters holds the list of output parameters produced by a step
     * @type {Array<IoArgoprojWorkflowV1alpha1Parameter>}
     * @memberof IoArgoprojWorkflowV1alpha1Outputs
     */
    parameters?: Array<IoArgoprojWorkflowV1alpha1Parameter>;
    /**
     * Result holds the result (stdout) of a script template
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Outputs
     */
    result?: string;
}
