// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1ArtifactLocation,
    IoArgoprojWorkflowV1alpha1DAGTemplate,
    IoArgoprojWorkflowV1alpha1Inputs,
    IoArgoprojWorkflowV1alpha1Metadata,
    IoArgoprojWorkflowV1alpha1Outputs,
    IoArgoprojWorkflowV1alpha1ResourceTemplate,
    IoArgoprojWorkflowV1alpha1RetryStrategy,
    IoArgoprojWorkflowV1alpha1ScriptTemplate,
    IoArgoprojWorkflowV1alpha1UserContainer,
    IoArgoprojWorkflowV1alpha1WorkflowStep,
    IoK8sApiCoreV1Affinity,
    IoK8sApiCoreV1Container,
    IoK8sApiCoreV1Toleration,
    IoK8sApiCoreV1Volume,
} from './';

/**
 * Template is a reusable and composable unit of execution in a workflow
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Template
 */
export interface IoArgoprojWorkflowV1alpha1Template {
    /**
     * Optional duration in seconds relative to the StartTime that the pod may be active on a node before the system actively tries to terminate the pod; value must be positive integer This field is only applicable to container and script templates.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    activeDeadlineSeconds?: number;
    /**
     * @type {IoK8sApiCoreV1Affinity}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    affinity?: IoK8sApiCoreV1Affinity;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ArtifactLocation}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    archiveLocation?: IoArgoprojWorkflowV1alpha1ArtifactLocation;
    /**
     * @type {IoK8sApiCoreV1Container}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    container?: IoK8sApiCoreV1Container;
    /**
     * Deamon will allow a workflow to proceed to the next step so long as the container reaches readiness
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    daemon?: boolean;
    /**
     * @type {IoArgoprojWorkflowV1alpha1DAGTemplate}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    dag?: IoArgoprojWorkflowV1alpha1DAGTemplate;
    /**
     * InitContainers is a list of containers which run before the main container.
     * @type {Array<IoArgoprojWorkflowV1alpha1UserContainer>}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    initContainers?: Array<IoArgoprojWorkflowV1alpha1UserContainer>;
    /**
     * @type {IoArgoprojWorkflowV1alpha1Inputs}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    inputs?: IoArgoprojWorkflowV1alpha1Inputs;
    /**
     * @type {IoArgoprojWorkflowV1alpha1Metadata}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    metadata?: IoArgoprojWorkflowV1alpha1Metadata;
    /**
     * Name is the name of the template
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    name: string;
    /**
     * NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level.
     * @type {{ [key: string]: string; }}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    nodeSelector?: { [key: string]: string; };
    /**
     * @type {IoArgoprojWorkflowV1alpha1Outputs}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    outputs?: IoArgoprojWorkflowV1alpha1Outputs;
    /**
     * Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    parallelism?: number;
    /**
     * Priority to apply to workflow pods.
     * @type {number}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    priority?: number;
    /**
     * PriorityClassName to apply to workflow pods.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    priorityClassName?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ResourceTemplate}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    resource?: IoArgoprojWorkflowV1alpha1ResourceTemplate;
    /**
     * @type {IoArgoprojWorkflowV1alpha1RetryStrategy}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    retryStrategy?: IoArgoprojWorkflowV1alpha1RetryStrategy;
    /**
     * If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler.
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    schedulerName?: string;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ScriptTemplate}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    script?: IoArgoprojWorkflowV1alpha1ScriptTemplate;
    /**
     * Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes
     * @type {Array<IoArgoprojWorkflowV1alpha1UserContainer>}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    sidecars?: Array<IoArgoprojWorkflowV1alpha1UserContainer>;
    /**
     * Steps define a series of sequential/parallel workflow steps
     * @type {Array<Array<IoArgoprojWorkflowV1alpha1WorkflowStep>>}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    steps?: Array<Array<IoArgoprojWorkflowV1alpha1WorkflowStep>>;
    /**
     * SuspendTemplate is a template subtype to suspend a workflow at a predetermined point in time
     * @type {object}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    suspend?: object;
    /**
     * Tolerations to apply to workflow pods.
     * @type {Array<IoK8sApiCoreV1Toleration>}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    tolerations?: Array<IoK8sApiCoreV1Toleration>;
    /**
     * Volumes is a list of volumes that can be mounted by containers in a template.
     * @type {Array<IoK8sApiCoreV1Volume>}
     * @memberof IoArgoprojWorkflowV1alpha1Template
     */
    volumes?: Array<IoK8sApiCoreV1Volume>;
}
