// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ContinueOn defines if a workflow should continue even if a task or step fails/errors. It can be specified if the workflow should continue when the pod errors, fails or both.
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ContinueOn
 */
export interface IoArgoprojWorkflowV1alpha1ContinueOn {
    /**
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1ContinueOn
     */
    error?: boolean;
    /**
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1ContinueOn
     */
    failed?: boolean;
}
