// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1SecretKeySelector,
} from './';

/**
 * GitArtifact is the location of an git artifact
 * @export
 * @interface IoArgoprojWorkflowV1alpha1GitArtifact
 */
export interface IoArgoprojWorkflowV1alpha1GitArtifact {
    /**
     * InsecureIgnoreHostKey disables SSH strict host key checking during git clone
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    insecureIgnoreHostKey?: boolean;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    passwordSecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * Repo is the git repository
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    repo: string;
    /**
     * Revision is the git commit, tag, branch to checkout
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    revision?: string;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    sshPrivateKeySecret?: IoK8sApiCoreV1SecretKeySelector;
    /**
     * @type {IoK8sApiCoreV1SecretKeySelector}
     * @memberof IoArgoprojWorkflowV1alpha1GitArtifact
     */
    usernameSecret?: IoK8sApiCoreV1SecretKeySelector;
}
