// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Pod metdata
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Metadata
 */
export interface IoArgoprojWorkflowV1alpha1Metadata {
    /**
     * @type {{ [key: string]: string; }}
     * @memberof IoArgoprojWorkflowV1alpha1Metadata
     */
    annotations?: { [key: string]: string; };
    /**
     * @type {{ [key: string]: string; }}
     * @memberof IoArgoprojWorkflowV1alpha1Metadata
     */
    labels?: { [key: string]: string; };
}
