// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sequence expands a workflow step into numeric range
 * @export
 * @interface IoArgoprojWorkflowV1alpha1Sequence
 */
export interface IoArgoprojWorkflowV1alpha1Sequence {
    /**
     * Count is number of elements in the sequence (default: 0). Not to be used with end
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Sequence
     */
    count?: string;
    /**
     * Number at which to end the sequence (default: 0). Not to be used with Count
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Sequence
     */
    end?: string;
    /**
     * Format is a printf format string to format the value in the sequence
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Sequence
     */
    format?: string;
    /**
     * Number at which to start the sequence (default: 0)
     * @type {string}
     * @memberof IoArgoprojWorkflowV1alpha1Sequence
     */
    start?: string;
}
