// tslint:disable
/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoArgoprojWorkflowV1alpha1ArtifactoryArtifact,
    IoArgoprojWorkflowV1alpha1GitArtifact,
    IoArgoprojWorkflowV1alpha1HDFSArtifact,
    IoArgoprojWorkflowV1alpha1HTTPArtifact,
    IoArgoprojWorkflowV1alpha1RawArtifact,
    IoArgoprojWorkflowV1alpha1S3Artifact,
} from './';

/**
 * ArtifactLocation describes a location for a single or multiple artifacts. It is used as single artifact in the context of inputs/outputs (e.g. outputs.artifacts.artname). It is also used to describe the location of multiple artifacts such as the archive location of a single workflow step, which the executor will use as a default location to store its files.
 * @export
 * @interface IoArgoprojWorkflowV1alpha1ArtifactLocation
 */
export interface IoArgoprojWorkflowV1alpha1ArtifactLocation {
    /**
     * ArchiveLogs indicates if the container logs should be archived
     * @type {boolean}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    archiveLogs?: boolean;
    /**
     * @type {IoArgoprojWorkflowV1alpha1ArtifactoryArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    artifactory?: IoArgoprojWorkflowV1alpha1ArtifactoryArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1GitArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    git?: IoArgoprojWorkflowV1alpha1GitArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1HDFSArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    hdfs?: IoArgoprojWorkflowV1alpha1HDFSArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1HTTPArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    http?: IoArgoprojWorkflowV1alpha1HTTPArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1RawArtifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    raw?: IoArgoprojWorkflowV1alpha1RawArtifact;
    /**
     * @type {IoArgoprojWorkflowV1alpha1S3Artifact}
     * @memberof IoArgoprojWorkflowV1alpha1ArtifactLocation
     */
    s3?: IoArgoprojWorkflowV1alpha1S3Artifact;
}
