// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NetworkPolicyPort describes a port to allow traffic on
 * @export
 * @interface IoK8sApiNetworkingV1NetworkPolicyPort
 */
export interface IoK8sApiNetworkingV1NetworkPolicyPort {
    /**
     * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
     * @type {string}
     * @memberof IoK8sApiNetworkingV1NetworkPolicyPort
     */
    port?: string;
    /**
     * The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
     * @type {string}
     * @memberof IoK8sApiNetworkingV1NetworkPolicyPort
     */
    protocol?: string;
}
