// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ScaleStatus represents the current status of a scale subresource.
 * @export
 * @interface IoK8sApiAutoscalingV1ScaleStatus
 */
export interface IoK8sApiAutoscalingV1ScaleStatus {
    /**
     * actual number of observed instances of the scaled object.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV1ScaleStatus
     */
    replicas: number;
    /**
     * label query over pods that should match the replicas count. This is same as the label selector but in the string format to avoid introspection by clients. The string will be in the same format as the query-param syntax. More info about label selectors: http://kubernetes.io/docs/user-guide/labels#label-selectors
     * @type {string}
     * @memberof IoK8sApiAutoscalingV1ScaleStatus
     */
    selector?: string;
}
