// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiPolicyV1beta1IDRange,
} from './';

/**
 * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
 * @export
 * @interface IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions
 */
export interface IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions {
    /**
     * ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.
     * @type {Array<IoK8sApiPolicyV1beta1IDRange>}
     * @memberof IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions
     */
    ranges?: Array<IoK8sApiPolicyV1beta1IDRange>;
    /**
     * rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions
     */
    rule?: string;
}
