// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReference,
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricTarget,
} from './';

/**
 * ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ObjectMetricSource
 */
export interface IoK8sApiAutoscalingV2beta2ObjectMetricSource {
    /**
     * @type {IoK8sApiAutoscalingV2beta2CrossVersionObjectReference}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricTarget}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    target: IoK8sApiAutoscalingV2beta2MetricTarget;
}
