// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiExtensionsV1beta1IPBlock,
    IoK8sApimachineryPkgApisMetaV1LabelSelector,
} from './';

/**
 * DEPRECATED 1.9 - This group version of NetworkPolicyPeer is deprecated by networking/v1/NetworkPolicyPeer.
 * @export
 * @interface IoK8sApiExtensionsV1beta1NetworkPolicyPeer
 */
export interface IoK8sApiExtensionsV1beta1NetworkPolicyPeer {
    /**
     * @type {IoK8sApiExtensionsV1beta1IPBlock}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyPeer
     */
    ipBlock?: IoK8sApiExtensionsV1beta1IPBlock;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyPeer
     */
    namespaceSelector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyPeer
     */
    podSelector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
}
