// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiExtensionsV1beta1IDRange,
} from './';

/**
 * FSGroupStrategyOptions defines the strategy type and options used to create the strategy. Deprecated: use FSGroupStrategyOptions from policy API Group instead.
 * @export
 * @interface IoK8sApiExtensionsV1beta1FSGroupStrategyOptions
 */
export interface IoK8sApiExtensionsV1beta1FSGroupStrategyOptions {
    /**
     * ranges are the allowed ranges of fs groups.  If you would like to force a single fs group then supply a single range with the same start and end. Required for MustRunAs.
     * @type {Array<IoK8sApiExtensionsV1beta1IDRange>}
     * @memberof IoK8sApiExtensionsV1beta1FSGroupStrategyOptions
     */
    ranges?: Array<IoK8sApiExtensionsV1beta1IDRange>;
    /**
     * rule is the strategy that will dictate what FSGroup is used in the SecurityContext.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1FSGroupStrategyOptions
     */
    rule?: string;
}
