// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec,
    IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * HorizontalPodAutoscaler is the configuration for a horizontal pod autoscaler, which automatically manages the replica count of any resource implementing the scale subresource based on the metrics specified.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
 */
export interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
     */
    spec?: IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec;
    /**
     * @type {IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscaler
     */
    status?: IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus;
}
