// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceSpec,
    IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceStatus,
} from './';

/**
 * APIService represents a server for a particular GroupVersion. Name must be \"version.group\".
 * @export
 * @interface IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
 */
export interface IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceSpec}
     * @memberof IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
     */
    spec?: IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceSpec;
    /**
     * @type {IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceStatus}
     * @memberof IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
     */
    status?: IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceStatus;
}
