// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1SecretReference,
} from './';

/**
 * Represents storage that is managed by an external CSI volume driver (Beta feature)
 * @export
 * @interface IoK8sApiCoreV1CSIPersistentVolumeSource
 */
export interface IoK8sApiCoreV1CSIPersistentVolumeSource {
    /**
     * @type {IoK8sApiCoreV1SecretReference}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    controllerExpandSecretRef?: IoK8sApiCoreV1SecretReference;
    /**
     * @type {IoK8sApiCoreV1SecretReference}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    controllerPublishSecretRef?: IoK8sApiCoreV1SecretReference;
    /**
     * Driver is the name of the driver to use for this volume. Required.
     * @type {string}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    driver: string;
    /**
     * Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\".
     * @type {string}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    fsType?: string;
    /**
     * @type {IoK8sApiCoreV1SecretReference}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    nodePublishSecretRef?: IoK8sApiCoreV1SecretReference;
    /**
     * @type {IoK8sApiCoreV1SecretReference}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    nodeStageSecretRef?: IoK8sApiCoreV1SecretReference;
    /**
     * Optional: The value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).
     * @type {boolean}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    readOnly?: boolean;
    /**
     * Attributes of the volume to publish.
     * @type {{ [key: string]: string; }}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    volumeAttributes?: { [key: string]: string; };
    /**
     * VolumeHandle is the unique volume name returned by the CSI volume plugin’s CreateVolume to refer to the volume on all subsequent calls. Required.
     * @type {string}
     * @memberof IoK8sApiCoreV1CSIPersistentVolumeSource
     */
    volumeHandle: string;
}
