// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NamespaceCondition contains details about state of namespace.
 * @export
 * @interface IoK8sApiCoreV1NamespaceCondition
 */
export interface IoK8sApiCoreV1NamespaceCondition {
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiCoreV1NamespaceCondition
     */
    lastTransitionTime?: Date;
    /**
     * @type {string}
     * @memberof IoK8sApiCoreV1NamespaceCondition
     */
    message?: string;
    /**
     * @type {string}
     * @memberof IoK8sApiCoreV1NamespaceCondition
     */
    reason?: string;
    /**
     * Status of the condition, one of True, False, Unknown.
     * @type {string}
     * @memberof IoK8sApiCoreV1NamespaceCondition
     */
    status: string;
    /**
     * Type of namespace controller condition.
     * @type {string}
     * @memberof IoK8sApiCoreV1NamespaceCondition
     */
    type: string;
}
