// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApimachineryPkgApisMetaV1LabelSelector,
} from './';

/**
 * MetricIdentifier defines the name and optionally selector for a metric
 * @export
 * @interface IoK8sApiAutoscalingV2beta2MetricIdentifier
 */
export interface IoK8sApiAutoscalingV2beta2MetricIdentifier {
    /**
     * name is the name of the given metric
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2MetricIdentifier
     */
    name: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiAutoscalingV2beta2MetricIdentifier
     */
    selector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
}
