// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition,
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources,
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation,
} from './';

/**
 * CustomResourceDefinitionVersion describes a version for CRD.
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion {
    /**
     * additionalPrinterColumns specifies additional columns returned in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for details. If no columns are specified, a single column displaying the age of the custom resource is used.
     * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    additionalPrinterColumns?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition>;
    /**
     * name is the version name, e.g. “v1”, “v2beta1”, etc. The custom resources are served under this version at `/apis/<group>/<version>/...` if `served` is true.
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    name: string;
    /**
     * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    schema?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation;
    /**
     * served is a flag enabling/disabling this version from being served via REST APIs
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    served: boolean;
    /**
     * storage indicates this version should be used when persisting custom resources to storage. There must be exactly one version with storage=true.
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    storage: boolean;
    /**
     * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
     */
    subresources?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources;
}
