// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Info contains versioning information. how we\'ll want to distribute that information.
 * @export
 * @interface IoK8sApimachineryPkgVersionInfo
 */
export interface IoK8sApimachineryPkgVersionInfo {
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    buildDate: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    compiler: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    gitCommit: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    gitTreeState: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    gitVersion: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    goVersion: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    major: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    minor: string;
    /**
     * @type {string}
     * @memberof IoK8sApimachineryPkgVersionInfo
     */
    platform: string;
}
