// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation,
} from './';

/**
 * JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps {
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    $ref?: string;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    $schema?: string;
    /**
     * JSONSchemaPropsOrBool represents JSONSchemaProps or a boolean value. Defaults to true for the boolean property.
     * @type {object}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    additionalItems?: object;
    /**
     * JSONSchemaPropsOrBool represents JSONSchemaProps or a boolean value. Defaults to true for the boolean property.
     * @type {object}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    additionalProperties?: object;
    /**
     * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    allOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>;
    /**
     * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    anyOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>;
    /**
     * JSON represents any valid JSON value. These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
     * @type {object}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    _default?: object;
    /**
     * @type {{ [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; }}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    definitions?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; };
    /**
     * @type {{ [key: string]: object; }}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    dependencies?: { [key: string]: object; };
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    description?: string;
    /**
     * @type {Array<object>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    _enum?: Array<object>;
    /**
     * JSON represents any valid JSON value. These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
     * @type {object}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    example?: object;
    /**
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    exclusiveMaximum?: boolean;
    /**
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    exclusiveMinimum?: boolean;
    /**
     * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    externalDocs?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    format?: string;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    id?: string;
    /**
     * JSONSchemaPropsOrArray represents a value that can either be a JSONSchemaProps or an array of JSONSchemaProps. Mainly here for serialization purposes.
     * @type {object}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    items?: object;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    maxItems?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    maxLength?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    maxProperties?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    maximum?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    minItems?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    minLength?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    minProperties?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    minimum?: number;
    /**
     * @type {number}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    multipleOf?: number;
    /**
     * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    not?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps;
    /**
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    nullable?: boolean;
    /**
     * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    oneOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps>;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    pattern?: string;
    /**
     * @type {{ [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; }}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    patternProperties?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; };
    /**
     * @type {{ [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; }}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    properties?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps; };
    /**
     * @type {Array<string>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    required?: Array<string>;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    title?: string;
    /**
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    type?: string;
    /**
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    uniqueItems?: boolean;
    /**
     * x-kubernetes-embedded-resource defines that the value is an embedded Kubernetes runtime.Object, with TypeMeta and ObjectMeta. The type must be object. It is allowed to further restrict the embedded object. kind, apiVersion and metadata are validated automatically. x-kubernetes-preserve-unknown-fields is allowed to be true, but does not have to be if the object is fully specified (up to kind, apiVersion, metadata).
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    xKubernetesEmbeddedResource?: boolean;
    /**
     * x-kubernetes-int-or-string specifies that this value is either an integer or a string. If this is true, an empty type is allowed and type as child of anyOf is permitted if following one of the following patterns:  1) anyOf:    - type: integer    - type: string 2) allOf:    - anyOf:      - type: integer      - type: string    - ... zero or more
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    xKubernetesIntOrString?: boolean;
    /**
     * x-kubernetes-list-map-keys annotates an array with the x-kubernetes-list-type `map` by specifying the keys used as the index of the map.  This tag MUST only be used on lists that have the \"x-kubernetes-list-type\" extension set to \"map\". Also, the values specified for this attribute must be a scalar typed field of the child structure (no nesting is supported).
     * @type {Array<string>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    xKubernetesListMapKeys?: Array<string>;
    /**
     * x-kubernetes-list-type annotates an array to further describe its topology. This extension must only be used on lists and may have 3 possible values:  1) `atomic`: the list is treated as a single entity, like a scalar.      Atomic lists will be entirely replaced when updated. This extension      may be used on any type of list (struct, scalar, ...). 2) `set`:      Sets are lists that must not have multiple items with the same value. Each      value must be a scalar (or another atomic type). 3) `map`:      These lists are like maps in that their elements have a non-index key      used to identify them. Order is preserved upon merge. The map tag      must only be used on a list with elements of type object. Defaults to atomic for arrays.
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    xKubernetesListType?: string;
    /**
     * x-kubernetes-preserve-unknown-fields stops the API server decoding step from pruning fields which are not specified in the validation schema. This affects fields recursively, but switches back to normal pruning behaviour if nested properties or additionalProperties are specified in the schema. This can either be true or undefined. False is forbidden.
     * @type {boolean}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
     */
    xKubernetesPreserveUnknownFields?: boolean;
}
