// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAuditregistrationV1alpha1Policy,
    IoK8sApiAuditregistrationV1alpha1Webhook,
} from './';

/**
 * AuditSinkSpec holds the spec for the audit sink
 * @export
 * @interface IoK8sApiAuditregistrationV1alpha1AuditSinkSpec
 */
export interface IoK8sApiAuditregistrationV1alpha1AuditSinkSpec {
    /**
     * @type {IoK8sApiAuditregistrationV1alpha1Policy}
     * @memberof IoK8sApiAuditregistrationV1alpha1AuditSinkSpec
     */
    policy: IoK8sApiAuditregistrationV1alpha1Policy;
    /**
     * @type {IoK8sApiAuditregistrationV1alpha1Webhook}
     * @memberof IoK8sApiAuditregistrationV1alpha1AuditSinkSpec
     */
    webhook: IoK8sApiAuditregistrationV1alpha1Webhook;
}
