// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec,
    IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * Describes a certificate signing request
 * @export
 * @interface IoK8sApiCertificatesV1beta1CertificateSigningRequest
 */
export interface IoK8sApiCertificatesV1beta1CertificateSigningRequest {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequest
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequest
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequest
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequest
     */
    spec?: IoK8sApiCertificatesV1beta1CertificateSigningRequestSpec;
    /**
     * @type {IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequest
     */
    status?: IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus;
}
