// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricTarget,
} from './';

/**
 * ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ExternalMetricSource
 */
export interface IoK8sApiAutoscalingV2beta2ExternalMetricSource {
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2ExternalMetricSource
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricTarget}
     * @memberof IoK8sApiAutoscalingV2beta2ExternalMetricSource
     */
    target: IoK8sApiAutoscalingV2beta2MetricTarget;
}
