// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps,
} from './';

/**
 * CustomResourceValidation is a list of validation methods for CustomResources.
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation {
    /**
     * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation
     */
    openAPIV3Schema?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps;
}
