// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * CrossVersionObjectReference contains enough information to let you identify the referred resource.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
 */
export interface IoK8sApiAutoscalingV2beta2CrossVersionObjectReference {
    /**
     * API version of the referent
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    apiVersion?: string;
    /**
     * Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds\"
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    kind: string;
    /**
     * Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    name: string;
}
