// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1LoadBalancerStatus,
} from './';

/**
 * ServiceStatus represents the current status of a service.
 * @export
 * @interface IoK8sApiCoreV1ServiceStatus
 */
export interface IoK8sApiCoreV1ServiceStatus {
    /**
     * @type {IoK8sApiCoreV1LoadBalancerStatus}
     * @memberof IoK8sApiCoreV1ServiceStatus
     */
    loadBalancer?: IoK8sApiCoreV1LoadBalancerStatus;
}
