// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2ExternalMetricSource,
    IoK8sApiAutoscalingV2beta2ObjectMetricSource,
    IoK8sApiAutoscalingV2beta2PodsMetricSource,
    IoK8sApiAutoscalingV2beta2ResourceMetricSource,
} from './';

/**
 * MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2MetricSpec
 */
export interface IoK8sApiAutoscalingV2beta2MetricSpec {
    /**
     * @type {IoK8sApiAutoscalingV2beta2ExternalMetricSource}
     * @memberof IoK8sApiAutoscalingV2beta2MetricSpec
     */
    external?: IoK8sApiAutoscalingV2beta2ExternalMetricSource;
    /**
     * @type {IoK8sApiAutoscalingV2beta2ObjectMetricSource}
     * @memberof IoK8sApiAutoscalingV2beta2MetricSpec
     */
    object?: IoK8sApiAutoscalingV2beta2ObjectMetricSource;
    /**
     * @type {IoK8sApiAutoscalingV2beta2PodsMetricSource}
     * @memberof IoK8sApiAutoscalingV2beta2MetricSpec
     */
    pods?: IoK8sApiAutoscalingV2beta2PodsMetricSource;
    /**
     * @type {IoK8sApiAutoscalingV2beta2ResourceMetricSource}
     * @memberof IoK8sApiAutoscalingV2beta2MetricSpec
     */
    resource?: IoK8sApiAutoscalingV2beta2ResourceMetricSource;
    /**
     * type is the type of metric source.  It should be one of \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object.
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2MetricSpec
     */
    type: string;
}
