// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAuditregistrationV1alpha1WebhookClientConfig,
    IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig,
} from './';

/**
 * Webhook holds the configuration of the webhook
 * @export
 * @interface IoK8sApiAuditregistrationV1alpha1Webhook
 */
export interface IoK8sApiAuditregistrationV1alpha1Webhook {
    /**
     * @type {IoK8sApiAuditregistrationV1alpha1WebhookClientConfig}
     * @memberof IoK8sApiAuditregistrationV1alpha1Webhook
     */
    clientConfig: IoK8sApiAuditregistrationV1alpha1WebhookClientConfig;
    /**
     * @type {IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig}
     * @memberof IoK8sApiAuditregistrationV1alpha1Webhook
     */
    throttle?: IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig;
}
