// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AllowedFlexVolume represents a single Flexvolume that is allowed to be used. Deprecated: use AllowedFlexVolume from policy API Group instead.
 * @export
 * @interface IoK8sApiExtensionsV1beta1AllowedFlexVolume
 */
export interface IoK8sApiExtensionsV1beta1AllowedFlexVolume {
    /**
     * driver is the name of the Flexvolume driver.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1AllowedFlexVolume
     */
    driver: string;
}
