// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApimachineryPkgApisMetaV1LabelSelector,
} from './';

/**
 * PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
 * @export
 * @interface IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec
 */
export interface IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec {
    /**
     * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec
     */
    maxUnavailable?: string;
    /**
     * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec
     */
    minAvailable?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec
     */
    selector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
}
