// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAppsV1beta2ReplicaSetSpec,
    IoK8sApiAppsV1beta2ReplicaSetStatus,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * DEPRECATED - This group version of ReplicaSet is deprecated by apps/v1/ReplicaSet. See the release notes for more information. ReplicaSet ensures that a specified number of pod replicas are running at any given time.
 * @export
 * @interface IoK8sApiAppsV1beta2ReplicaSet
 */
export interface IoK8sApiAppsV1beta2ReplicaSet {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sApiAppsV1beta2ReplicaSetSpec}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    spec?: IoK8sApiAppsV1beta2ReplicaSetSpec;
    /**
     * @type {IoK8sApiAppsV1beta2ReplicaSetStatus}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    status?: IoK8sApiAppsV1beta2ReplicaSetStatus;
}
