// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * StatefulSetCondition describes the state of a statefulset at a certain point.
 * @export
 * @interface IoK8sApiAppsV1beta1StatefulSetCondition
 */
export interface IoK8sApiAppsV1beta1StatefulSetCondition {
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiAppsV1beta1StatefulSetCondition
     */
    lastTransitionTime?: Date;
    /**
     * A human readable message indicating details about the transition.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta1StatefulSetCondition
     */
    message?: string;
    /**
     * The reason for the condition\'s last transition.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta1StatefulSetCondition
     */
    reason?: string;
    /**
     * Status of the condition, one of True, False, Unknown.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta1StatefulSetCondition
     */
    status: string;
    /**
     * Type of statefulset condition.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta1StatefulSetCondition
     */
    type: string;
}
