// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VolumeError captures an error encountered during a volume operation.
 * @export
 * @interface IoK8sApiStorageV1alpha1VolumeError
 */
export interface IoK8sApiStorageV1alpha1VolumeError {
    /**
     * String detailing the error encountered during Attach or Detach operation. This string maybe logged, so it should not contain sensitive information.
     * @type {string}
     * @memberof IoK8sApiStorageV1alpha1VolumeError
     */
    message?: string;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiStorageV1alpha1VolumeError
     */
    time?: Date;
}
