// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAuthorizationV1beta1NonResourceAttributes,
    IoK8sApiAuthorizationV1beta1ResourceAttributes,
} from './';

/**
 * SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
 * @export
 * @interface IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec
 */
export interface IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec {
    /**
     * @type {IoK8sApiAuthorizationV1beta1NonResourceAttributes}
     * @memberof IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec
     */
    nonResourceAttributes?: IoK8sApiAuthorizationV1beta1NonResourceAttributes;
    /**
     * @type {IoK8sApiAuthorizationV1beta1ResourceAttributes}
     * @memberof IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewSpec
     */
    resourceAttributes?: IoK8sApiAuthorizationV1beta1ResourceAttributes;
}
