// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition,
} from './';

/**
 * @export
 * @interface IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus
 */
export interface IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus {
    /**
     * If request was approved, the controller will place the issued certificate here.
     * @type {string}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus
     */
    certificate?: string;
    /**
     * Conditions applied to the request, such as approval or denial.
     * @type {Array<IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition>}
     * @memberof IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus
     */
    conditions?: Array<IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition>;
}
