// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiPolicyV1beta1IDRange,
} from './';

/**
 * RunAsUserStrategyOptions defines the strategy type and any options used to create the strategy.
 * @export
 * @interface IoK8sApiPolicyV1beta1RunAsUserStrategyOptions
 */
export interface IoK8sApiPolicyV1beta1RunAsUserStrategyOptions {
    /**
     * ranges are the allowed ranges of uids that may be used. If you would like to force a single uid then supply a single range with the same start and end. Required for MustRunAs.
     * @type {Array<IoK8sApiPolicyV1beta1IDRange>}
     * @memberof IoK8sApiPolicyV1beta1RunAsUserStrategyOptions
     */
    ranges?: Array<IoK8sApiPolicyV1beta1IDRange>;
    /**
     * rule is the strategy that will dictate the allowable RunAsUser values that may be set.
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1RunAsUserStrategyOptions
     */
    rule: string;
}
