// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1EventSource,
    IoK8sApiCoreV1ObjectReference,
    IoK8sApiEventsV1beta1EventSeries,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * Event is a report of an event somewhere in the cluster. It generally denotes some state change in the system.
 * @export
 * @interface IoK8sApiEventsV1beta1Event
 */
export interface IoK8sApiEventsV1beta1Event {
    /**
     * What action was taken/failed regarding to the regarding object.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    action?: string;
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    apiVersion?: string;
    /**
     * Deprecated field assuring backward compatibility with core.v1 Event type
     * @type {number}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    deprecatedCount?: number;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    deprecatedFirstTimestamp?: Date;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    deprecatedLastTimestamp?: Date;
    /**
     * @type {IoK8sApiCoreV1EventSource}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    deprecatedSource?: IoK8sApiCoreV1EventSource;
    /**
     * MicroTime is version of Time with microsecond level precision.
     * @type {Date}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    eventTime: Date;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * Optional. A human-readable description of the status of this operation. Maximal length of the note is 1kB, but libraries should be prepared to handle values up to 64kB.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    note?: string;
    /**
     * Why the action was taken.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    reason?: string;
    /**
     * @type {IoK8sApiCoreV1ObjectReference}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    regarding?: IoK8sApiCoreV1ObjectReference;
    /**
     * @type {IoK8sApiCoreV1ObjectReference}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    related?: IoK8sApiCoreV1ObjectReference;
    /**
     * Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    reportingController?: string;
    /**
     * ID of the controller instance, e.g. `kubelet-xyzf`.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    reportingInstance?: string;
    /**
     * @type {IoK8sApiEventsV1beta1EventSeries}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    series?: IoK8sApiEventsV1beta1EventSeries;
    /**
     * Type of this event (Normal, Warning), new types could be added in the future.
     * @type {string}
     * @memberof IoK8sApiEventsV1beta1Event
     */
    type?: string;
}
