// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet,
} from './';

/**
 * @export
 * @interface IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
 */
export interface IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy {
    /**
     * @type {IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet}
     * @memberof IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
     */
    rollingUpdate?: IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet;
    /**
     * Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is OnDelete.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
     */
    type?: string;
}
