// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewSpec
 */
export interface IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewSpec {
    /**
     * Namespace to evaluate rules for. Required.
     * @type {string}
     * @memberof IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewSpec
     */
    namespace?: string;
}
