// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec,
    IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * PodDisruptionBudget is an object to define the max disruption that can be caused to a collection of pods
 * @export
 * @interface IoK8sApiPolicyV1beta1PodDisruptionBudget
 */
export interface IoK8sApiPolicyV1beta1PodDisruptionBudget {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudget
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudget
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudget
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudget
     */
    spec?: IoK8sApiPolicyV1beta1PodDisruptionBudgetSpec;
    /**
     * @type {IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus}
     * @memberof IoK8sApiPolicyV1beta1PodDisruptionBudget
     */
    status?: IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus;
}
