// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1EnvFromSource,
    IoK8sApiCoreV1EnvVar,
    IoK8sApiCoreV1Volume,
    IoK8sApiCoreV1VolumeMount,
    IoK8sApimachineryPkgApisMetaV1LabelSelector,
} from './';

/**
 * PodPresetSpec is a description of a pod preset.
 * @export
 * @interface IoK8sApiSettingsV1alpha1PodPresetSpec
 */
export interface IoK8sApiSettingsV1alpha1PodPresetSpec {
    /**
     * Env defines the collection of EnvVar to inject into containers.
     * @type {Array<IoK8sApiCoreV1EnvVar>}
     * @memberof IoK8sApiSettingsV1alpha1PodPresetSpec
     */
    env?: Array<IoK8sApiCoreV1EnvVar>;
    /**
     * EnvFrom defines the collection of EnvFromSource to inject into containers.
     * @type {Array<IoK8sApiCoreV1EnvFromSource>}
     * @memberof IoK8sApiSettingsV1alpha1PodPresetSpec
     */
    envFrom?: Array<IoK8sApiCoreV1EnvFromSource>;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiSettingsV1alpha1PodPresetSpec
     */
    selector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
    /**
     * VolumeMounts defines the collection of VolumeMount to inject into containers.
     * @type {Array<IoK8sApiCoreV1VolumeMount>}
     * @memberof IoK8sApiSettingsV1alpha1PodPresetSpec
     */
    volumeMounts?: Array<IoK8sApiCoreV1VolumeMount>;
    /**
     * Volumes defines the collection of Volume to inject into the pod.
     * @type {Array<IoK8sApiCoreV1Volume>}
     * @memberof IoK8sApiSettingsV1alpha1PodPresetSpec
     */
    volumes?: Array<IoK8sApiCoreV1Volume>;
}
