// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describe a container image
 * @export
 * @interface IoK8sApiCoreV1ContainerImage
 */
export interface IoK8sApiCoreV1ContainerImage {
    /**
     * Names by which this image is known. e.g. [\"k8s.gcr.io/hyperkube:v1.0.7\", \"dockerhub.io/google_containers/hyperkube:v1.0.7\"]
     * @type {Array<string>}
     * @memberof IoK8sApiCoreV1ContainerImage
     */
    names: Array<string>;
    /**
     * The size of the image in bytes.
     * @type {number}
     * @memberof IoK8sApiCoreV1ContainerImage
     */
    sizeBytes?: number;
}
