// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAppsV1beta1RollingUpdateDeployment,
} from './';

/**
 * DeploymentStrategy describes how to replace existing pods with new ones.
 * @export
 * @interface IoK8sApiAppsV1beta1DeploymentStrategy
 */
export interface IoK8sApiAppsV1beta1DeploymentStrategy {
    /**
     * @type {IoK8sApiAppsV1beta1RollingUpdateDeployment}
     * @memberof IoK8sApiAppsV1beta1DeploymentStrategy
     */
    rollingUpdate?: IoK8sApiAppsV1beta1RollingUpdateDeployment;
    /**
     * Type of deployment. Can be \"Recreate\" or \"RollingUpdate\". Default is RollingUpdate.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta1DeploymentStrategy
     */
    type?: string;
}
