// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2ExternalMetricStatus,
    IoK8sApiAutoscalingV2beta2ObjectMetricStatus,
    IoK8sApiAutoscalingV2beta2PodsMetricStatus,
    IoK8sApiAutoscalingV2beta2ResourceMetricStatus,
} from './';

/**
 * MetricStatus describes the last-read state of a single metric.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2MetricStatus
 */
export interface IoK8sApiAutoscalingV2beta2MetricStatus {
    /**
     * @type {IoK8sApiAutoscalingV2beta2ExternalMetricStatus}
     * @memberof IoK8sApiAutoscalingV2beta2MetricStatus
     */
    external?: IoK8sApiAutoscalingV2beta2ExternalMetricStatus;
    /**
     * @type {IoK8sApiAutoscalingV2beta2ObjectMetricStatus}
     * @memberof IoK8sApiAutoscalingV2beta2MetricStatus
     */
    object?: IoK8sApiAutoscalingV2beta2ObjectMetricStatus;
    /**
     * @type {IoK8sApiAutoscalingV2beta2PodsMetricStatus}
     * @memberof IoK8sApiAutoscalingV2beta2MetricStatus
     */
    pods?: IoK8sApiAutoscalingV2beta2PodsMetricStatus;
    /**
     * @type {IoK8sApiAutoscalingV2beta2ResourceMetricStatus}
     * @memberof IoK8sApiAutoscalingV2beta2MetricStatus
     */
    resource?: IoK8sApiAutoscalingV2beta2ResourceMetricStatus;
    /**
     * type is the type of metric source.  It will be one of \"Object\", \"Pods\" or \"Resource\", each corresponds to a matching field in the object.
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2MetricStatus
     */
    type: string;
}
