// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1AttachedVolume,
    IoK8sApiCoreV1ContainerImage,
    IoK8sApiCoreV1NodeAddress,
    IoK8sApiCoreV1NodeCondition,
    IoK8sApiCoreV1NodeConfigStatus,
    IoK8sApiCoreV1NodeDaemonEndpoints,
    IoK8sApiCoreV1NodeSystemInfo,
} from './';

/**
 * NodeStatus is information about the current status of a node.
 * @export
 * @interface IoK8sApiCoreV1NodeStatus
 */
export interface IoK8sApiCoreV1NodeStatus {
    /**
     * List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses Note: This field is declared as mergeable, but the merge key is not sufficiently unique, which can cause data corruption when it is merged. Callers should instead use a full-replacement patch. See http://pr.k8s.io/79391 for an example.
     * @type {Array<IoK8sApiCoreV1NodeAddress>}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    addresses?: Array<IoK8sApiCoreV1NodeAddress>;
    /**
     * Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.
     * @type {{ [key: string]: string; }}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    allocatable?: { [key: string]: string; };
    /**
     * Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity
     * @type {{ [key: string]: string; }}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    capacity?: { [key: string]: string; };
    /**
     * Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/concepts/nodes/node/#condition
     * @type {Array<IoK8sApiCoreV1NodeCondition>}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    conditions?: Array<IoK8sApiCoreV1NodeCondition>;
    /**
     * @type {IoK8sApiCoreV1NodeConfigStatus}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    config?: IoK8sApiCoreV1NodeConfigStatus;
    /**
     * @type {IoK8sApiCoreV1NodeDaemonEndpoints}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    daemonEndpoints?: IoK8sApiCoreV1NodeDaemonEndpoints;
    /**
     * List of container images on this node
     * @type {Array<IoK8sApiCoreV1ContainerImage>}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    images?: Array<IoK8sApiCoreV1ContainerImage>;
    /**
     * @type {IoK8sApiCoreV1NodeSystemInfo}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    nodeInfo?: IoK8sApiCoreV1NodeSystemInfo;
    /**
     * NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated.
     * @type {string}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    phase?: string;
    /**
     * List of volumes that are attached to the node.
     * @type {Array<IoK8sApiCoreV1AttachedVolume>}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    volumesAttached?: Array<IoK8sApiCoreV1AttachedVolume>;
    /**
     * List of attachable volumes in use (mounted) by the node.
     * @type {Array<string>}
     * @memberof IoK8sApiCoreV1NodeStatus
     */
    volumesInUse?: Array<string>;
}
