// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiExtensionsV1beta1NetworkPolicy,
    IoK8sApimachineryPkgApisMetaV1ListMeta,
} from './';

/**
 * DEPRECATED 1.9 - This group version of NetworkPolicyList is deprecated by networking/v1/NetworkPolicyList. Network Policy List is a list of NetworkPolicy objects.
 * @export
 * @interface IoK8sApiExtensionsV1beta1NetworkPolicyList
 */
export interface IoK8sApiExtensionsV1beta1NetworkPolicyList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyList
     */
    apiVersion?: string;
    /**
     * Items is a list of schema objects.
     * @type {Array<IoK8sApiExtensionsV1beta1NetworkPolicy>}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyList
     */
    items: Array<IoK8sApiExtensionsV1beta1NetworkPolicy>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyList
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyList
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}
