// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReference,
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricValueStatus,
} from './';

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ObjectMetricStatus
 */
export interface IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricValueStatus}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
     */
    current: IoK8sApiAutoscalingV2beta2MetricValueStatus;
    /**
     * @type {IoK8sApiAutoscalingV2beta2CrossVersionObjectReference}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
     */
    describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
}
