// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiStorageV1VolumeAttachmentSource,
} from './';

/**
 * VolumeAttachmentSpec is the specification of a VolumeAttachment request.
 * @export
 * @interface IoK8sApiStorageV1VolumeAttachmentSpec
 */
export interface IoK8sApiStorageV1VolumeAttachmentSpec {
    /**
     * Attacher indicates the name of the volume driver that MUST handle this request. This is the name returned by GetPluginName().
     * @type {string}
     * @memberof IoK8sApiStorageV1VolumeAttachmentSpec
     */
    attacher: string;
    /**
     * The node that the volume should be attached to.
     * @type {string}
     * @memberof IoK8sApiStorageV1VolumeAttachmentSpec
     */
    nodeName: string;
    /**
     * @type {IoK8sApiStorageV1VolumeAttachmentSource}
     * @memberof IoK8sApiStorageV1VolumeAttachmentSpec
     */
    source: IoK8sApiStorageV1VolumeAttachmentSource;
}
