// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReference,
    IoK8sApiAutoscalingV2beta2MetricSpec,
} from './';

/**
 * HorizontalPodAutoscalerSpec describes the desired functionality of the HorizontalPodAutoscaler.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec
 */
export interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec {
    /**
     * maxReplicas is the upper limit for the number of replicas to which the autoscaler can scale up. It cannot be less that minReplicas.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec
     */
    maxReplicas: number;
    /**
     * metrics contains the specifications for which to use to calculate the desired replica count (the maximum replica count across all metrics will be used).  The desired replica count is calculated multiplying the ratio between the target value and the current value by the current number of pods.  Ergo, metrics used must decrease as the pod count is increased, and vice-versa.  See the individual metric source types for more information about how each type of metric must respond. If not set, the default metric will be set to 80% average CPU utilization.
     * @type {Array<IoK8sApiAutoscalingV2beta2MetricSpec>}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec
     */
    metrics?: Array<IoK8sApiAutoscalingV2beta2MetricSpec>;
    /**
     * minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down.  It defaults to 1 pod.  minReplicas is allowed to be 0 if the alpha feature gate HPAScaleToZero is enabled and at least one Object or External metric is configured.  Scaling is active as long as at least one metric value is available.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec
     */
    minReplicas?: number;
    /**
     * @type {IoK8sApiAutoscalingV2beta2CrossVersionObjectReference}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerSpec
     */
    scaleTargetRef: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
}
