// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiNodeV1alpha1Overhead,
    IoK8sApiNodeV1alpha1Scheduling,
} from './';

/**
 * RuntimeClassSpec is a specification of a RuntimeClass. It contains parameters that are required to describe the RuntimeClass to the Container Runtime Interface (CRI) implementation, as well as any other components that need to understand how the pod will be run. The RuntimeClassSpec is immutable.
 * @export
 * @interface IoK8sApiNodeV1alpha1RuntimeClassSpec
 */
export interface IoK8sApiNodeV1alpha1RuntimeClassSpec {
    /**
     * @type {IoK8sApiNodeV1alpha1Overhead}
     * @memberof IoK8sApiNodeV1alpha1RuntimeClassSpec
     */
    overhead?: IoK8sApiNodeV1alpha1Overhead;
    /**
     * RuntimeHandler specifies the underlying runtime and configuration that the CRI implementation will use to handle pods of this class. The possible values are specific to the node & CRI configuration.  It is assumed that all handlers are available on every node, and handlers of the same name are equivalent on every node. For example, a handler called \"runc\" might specify that the runc OCI runtime (using native Linux containers) will be used to run the containers in a pod. The RuntimeHandler must conform to the DNS Label (RFC 1123) requirements and is immutable.
     * @type {string}
     * @memberof IoK8sApiNodeV1alpha1RuntimeClassSpec
     */
    runtimeHandler: string;
    /**
     * @type {IoK8sApiNodeV1alpha1Scheduling}
     * @memberof IoK8sApiNodeV1alpha1RuntimeClassSpec
     */
    scheduling?: IoK8sApiNodeV1alpha1Scheduling;
}
