// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAppsV1beta1DeploymentStrategy,
    IoK8sApiAppsV1beta1RollbackConfig,
    IoK8sApiCoreV1PodTemplateSpec,
    IoK8sApimachineryPkgApisMetaV1LabelSelector,
} from './';

/**
 * DeploymentSpec is the specification of the desired behavior of the Deployment.
 * @export
 * @interface IoK8sApiAppsV1beta1DeploymentSpec
 */
export interface IoK8sApiAppsV1beta1DeploymentSpec {
    /**
     * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
     * @type {number}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    minReadySeconds?: number;
    /**
     * Indicates that the deployment is paused.
     * @type {boolean}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    paused?: boolean;
    /**
     * The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    progressDeadlineSeconds?: number;
    /**
     * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    replicas?: number;
    /**
     * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 2.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    revisionHistoryLimit?: number;
    /**
     * @type {IoK8sApiAppsV1beta1RollbackConfig}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    rollbackTo?: IoK8sApiAppsV1beta1RollbackConfig;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1LabelSelector}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    selector?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
    /**
     * @type {IoK8sApiAppsV1beta1DeploymentStrategy}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    strategy?: IoK8sApiAppsV1beta1DeploymentStrategy;
    /**
     * @type {IoK8sApiCoreV1PodTemplateSpec}
     * @memberof IoK8sApiAppsV1beta1DeploymentSpec
     */
    template: IoK8sApiCoreV1PodTemplateSpec;
}
