// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricValueStatus,
} from './';

/**
 * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale target (for example, transactions-processed-per-second).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2PodsMetricStatus
 */
export interface IoK8sApiAutoscalingV2beta2PodsMetricStatus {
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricValueStatus}
     * @memberof IoK8sApiAutoscalingV2beta2PodsMetricStatus
     */
    current: IoK8sApiAutoscalingV2beta2MetricValueStatus;
    /**
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2PodsMetricStatus
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
}
