// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Overhead structure represents the resource overhead associated with running a pod.
 * @export
 * @interface IoK8sApiNodeV1beta1Overhead
 */
export interface IoK8sApiNodeV1beta1Overhead {
    /**
     * PodFixed represents the fixed resource overhead associated with running a pod.
     * @type {{ [key: string]: string; }}
     * @memberof IoK8sApiNodeV1beta1Overhead
     */
    podFixed?: { [key: string]: string; };
}
