// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * WebhookThrottleConfig holds the configuration for throttling events
 * @export
 * @interface IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig
 */
export interface IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig {
    /**
     * ThrottleBurst is the maximum number of events sent at the same moment default 15 QPS
     * @type {number}
     * @memberof IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig
     */
    burst?: number;
    /**
     * ThrottleQPS maximum number of batches per second default 10 QPS
     * @type {number}
     * @memberof IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig
     */
    qps?: number;
}
