// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PersistentVolumeStatus is the current status of a persistent volume.
 * @export
 * @interface IoK8sApiCoreV1PersistentVolumeStatus
 */
export interface IoK8sApiCoreV1PersistentVolumeStatus {
    /**
     * A human-readable message indicating details about why the volume is in this state.
     * @type {string}
     * @memberof IoK8sApiCoreV1PersistentVolumeStatus
     */
    message?: string;
    /**
     * Phase indicates if a volume is available, bound to a claim, or released by a claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#phase
     * @type {string}
     * @memberof IoK8sApiCoreV1PersistentVolumeStatus
     */
    phase?: string;
    /**
     * Reason is a brief CamelCase string that describes any failure and is meant for machine parsing and tidy display in the CLI.
     * @type {string}
     * @memberof IoK8sApiCoreV1PersistentVolumeStatus
     */
    reason?: string;
}
