// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ConfigMapNodeConfigSource contains the information to reference a ConfigMap as a config source for the Node.
 * @export
 * @interface IoK8sApiCoreV1ConfigMapNodeConfigSource
 */
export interface IoK8sApiCoreV1ConfigMapNodeConfigSource {
    /**
     * KubeletConfigKey declares which key of the referenced ConfigMap corresponds to the KubeletConfiguration structure This field is required in all cases.
     * @type {string}
     * @memberof IoK8sApiCoreV1ConfigMapNodeConfigSource
     */
    kubeletConfigKey: string;
    /**
     * Name is the metadata.name of the referenced ConfigMap. This field is required in all cases.
     * @type {string}
     * @memberof IoK8sApiCoreV1ConfigMapNodeConfigSource
     */
    name: string;
    /**
     * Namespace is the metadata.namespace of the referenced ConfigMap. This field is required in all cases.
     * @type {string}
     * @memberof IoK8sApiCoreV1ConfigMapNodeConfigSource
     */
    namespace: string;
    /**
     * ResourceVersion is the metadata.ResourceVersion of the referenced ConfigMap. This field is forbidden in Node.Spec, and required in Node.Status.
     * @type {string}
     * @memberof IoK8sApiCoreV1ConfigMapNodeConfigSource
     */
    resourceVersion?: string;
    /**
     * UID is the metadata.UID of the referenced ConfigMap. This field is forbidden in Node.Spec, and required in Node.Status.
     * @type {string}
     * @memberof IoK8sApiCoreV1ConfigMapNodeConfigSource
     */
    uid?: string;
}
