// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAppsV1beta2DaemonSetCondition,
} from './';

/**
 * DaemonSetStatus represents the current status of a daemon set.
 * @export
 * @interface IoK8sApiAppsV1beta2DaemonSetStatus
 */
export interface IoK8sApiAppsV1beta2DaemonSetStatus {
    /**
     * Count of hash collisions for the DaemonSet. The DaemonSet controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ControllerRevision.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    collisionCount?: number;
    /**
     * Represents the latest available observations of a DaemonSet\'s current state.
     * @type {Array<IoK8sApiAppsV1beta2DaemonSetCondition>}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    conditions?: Array<IoK8sApiAppsV1beta2DaemonSetCondition>;
    /**
     * The number of nodes that are running at least 1 daemon pod and are supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    currentNumberScheduled: number;
    /**
     * The total number of nodes that should be running the daemon pod (including nodes correctly running the daemon pod). More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    desiredNumberScheduled: number;
    /**
     * The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds)
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    numberAvailable?: number;
    /**
     * The number of nodes that are running the daemon pod, but are not supposed to run the daemon pod. More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    numberMisscheduled: number;
    /**
     * The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and ready.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    numberReady: number;
    /**
     * The number of nodes that should be running the daemon pod and have none of the daemon pod running and available (ready for at least spec.minReadySeconds)
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    numberUnavailable?: number;
    /**
     * The most recent generation observed by the daemon set controller.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    observedGeneration?: number;
    /**
     * The total number of nodes that are running updated daemon pod
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2DaemonSetStatus
     */
    updatedNumberScheduled?: number;
}
