// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition,
    IoK8sApiAutoscalingV2beta2MetricStatus,
} from './';

/**
 * HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
 */
export interface IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus {
    /**
     * conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.
     * @type {Array<IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition>}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    conditions: Array<IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition>;
    /**
     * currentMetrics is the last read state of the metrics used by this autoscaler.
     * @type {Array<IoK8sApiAutoscalingV2beta2MetricStatus>}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    currentMetrics?: Array<IoK8sApiAutoscalingV2beta2MetricStatus>;
    /**
     * currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    currentReplicas: number;
    /**
     * desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    desiredReplicas: number;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    lastScaleTime?: Date;
    /**
     * observedGeneration is the most recent generation observed by this autoscaler.
     * @type {number}
     * @memberof IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus
     */
    observedGeneration?: number;
}
