// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiPolicyV1beta1PodSecurityPolicy,
    IoK8sApimachineryPkgApisMetaV1ListMeta,
} from './';

/**
 * PodSecurityPolicyList is a list of PodSecurityPolicy objects.
 * @export
 * @interface IoK8sApiPolicyV1beta1PodSecurityPolicyList
 */
export interface IoK8sApiPolicyV1beta1PodSecurityPolicyList {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodSecurityPolicyList
     */
    apiVersion?: string;
    /**
     * items is a list of schema objects.
     * @type {Array<IoK8sApiPolicyV1beta1PodSecurityPolicy>}
     * @memberof IoK8sApiPolicyV1beta1PodSecurityPolicyList
     */
    items: Array<IoK8sApiPolicyV1beta1PodSecurityPolicy>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiPolicyV1beta1PodSecurityPolicyList
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
     * @memberof IoK8sApiPolicyV1beta1PodSecurityPolicyList
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}
