// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ContainerStateTerminated is a terminated state of a container.
 * @export
 * @interface IoK8sApiCoreV1ContainerStateTerminated
 */
export interface IoK8sApiCoreV1ContainerStateTerminated {
    /**
     * Container\'s ID in the format \'docker://<container_id>\'
     * @type {string}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    containerID?: string;
    /**
     * Exit status from the last termination of the container
     * @type {number}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    exitCode: number;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    finishedAt?: Date;
    /**
     * Message regarding the last termination of the container
     * @type {string}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    message?: string;
    /**
     * (brief) reason from the last termination of the container
     * @type {string}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    reason?: string;
    /**
     * Signal from the last termination of the container
     * @type {number}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    signal?: number;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiCoreV1ContainerStateTerminated
     */
    startedAt?: Date;
}
