// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EndpointPort represents a Port used by an EndpointSlice
 * @export
 * @interface IoK8sApiDiscoveryV1alpha1EndpointPort
 */
export interface IoK8sApiDiscoveryV1alpha1EndpointPort {
    /**
     * The name of this port. All ports in an EndpointSlice must have a unique name. If the EndpointSlice is dervied from a Kubernetes service, this corresponds to the Service.ports[].name. Name must either be an empty string or pass IANA_SVC_NAME validation: * must be no more than 15 characters long * may contain only [-a-z0-9] * must contain at least one letter [a-z] * it must not start or end with a hyphen, nor contain adjacent hyphens Default is empty string.
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointPort
     */
    name?: string;
    /**
     * The port number of the endpoint. If this is not specified, ports are not restricted and must be interpreted in the context of the specific consumer.
     * @type {number}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointPort
     */
    port?: number;
    /**
     * The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointPort
     */
    protocol?: string;
}
