// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiRbacV1alpha1RoleRef,
    IoK8sApiRbacV1alpha1Subject,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * ClusterRoleBinding references a ClusterRole, but not contain it.  It can reference a ClusterRole in the global namespace, and adds who information via Subject.
 * @export
 * @interface IoK8sApiRbacV1alpha1ClusterRoleBinding
 */
export interface IoK8sApiRbacV1alpha1ClusterRoleBinding {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiRbacV1alpha1ClusterRoleBinding
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiRbacV1alpha1ClusterRoleBinding
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiRbacV1alpha1ClusterRoleBinding
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * @type {IoK8sApiRbacV1alpha1RoleRef}
     * @memberof IoK8sApiRbacV1alpha1ClusterRoleBinding
     */
    roleRef: IoK8sApiRbacV1alpha1RoleRef;
    /**
     * Subjects holds references to the objects the role applies to.
     * @type {Array<IoK8sApiRbacV1alpha1Subject>}
     * @memberof IoK8sApiRbacV1alpha1ClusterRoleBinding
     */
    subjects?: Array<IoK8sApiRbacV1alpha1Subject>;
}
