// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiCoreV1ObjectReference,
    IoK8sApiDiscoveryV1alpha1EndpointConditions,
} from './';

/**
 * Endpoint represents a single logical \"backend\" implementing a service.
 * @export
 * @interface IoK8sApiDiscoveryV1alpha1Endpoint
 */
export interface IoK8sApiDiscoveryV1alpha1Endpoint {
    /**
     * addresses of this endpoint. The contents of this field are interpreted according to the corresponding EndpointSlice addressType field. This allows for cases like dual-stack (IPv4 and IPv6) networking. Consumers (e.g. kube-proxy) must handle different types of addresses in the context of their own capabilities. This must contain at least one address but no more than 100.
     * @type {Array<string>}
     * @memberof IoK8sApiDiscoveryV1alpha1Endpoint
     */
    addresses: Array<string>;
    /**
     * @type {IoK8sApiDiscoveryV1alpha1EndpointConditions}
     * @memberof IoK8sApiDiscoveryV1alpha1Endpoint
     */
    conditions?: IoK8sApiDiscoveryV1alpha1EndpointConditions;
    /**
     * hostname of this endpoint. This field may be used by consumers of endpoints to distinguish endpoints from each other (e.g. in DNS names). Multiple endpoints which use the same hostname should be considered fungible (e.g. multiple A values in DNS). Must pass DNS Label (RFC 1123) validation.
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1Endpoint
     */
    hostname?: string;
    /**
     * @type {IoK8sApiCoreV1ObjectReference}
     * @memberof IoK8sApiDiscoveryV1alpha1Endpoint
     */
    targetRef?: IoK8sApiCoreV1ObjectReference;
    /**
     * topology contains arbitrary topology information associated with the endpoint. These key/value pairs must conform with the label format. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels Topology may include a maximum of 16 key/value pairs. This includes, but is not limited to the following well known keys: * kubernetes.io/hostname: the value indicates the hostname of the node   where the endpoint is located. This should match the corresponding   node label. * topology.kubernetes.io/zone: the value indicates the zone where the   endpoint is located. This should match the corresponding node label. * topology.kubernetes.io/region: the value indicates the region where the   endpoint is located. This should match the corresponding node label.
     * @type {{ [key: string]: string; }}
     * @memberof IoK8sApiDiscoveryV1alpha1Endpoint
     */
    topology?: { [key: string]: string; };
}
