// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IoK8sApiDiscoveryV1alpha1Endpoint,
    IoK8sApiDiscoveryV1alpha1EndpointPort,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * EndpointSlice represents a subset of the endpoints that implement a service. For a given service there may be multiple EndpointSlice objects, selected by labels, which must be joined to produce the full set of endpoints.
 * @export
 * @interface IoK8sApiDiscoveryV1alpha1EndpointSlice
 */
export interface IoK8sApiDiscoveryV1alpha1EndpointSlice {
    /**
     * addressType specifies the type of address carried by this EndpointSlice. All addresses in this slice must be the same type. Default is IP
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    addressType?: string;
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    apiVersion?: string;
    /**
     * endpoints is a list of unique endpoints in this slice. Each slice may include a maximum of 1000 endpoints.
     * @type {Array<IoK8sApiDiscoveryV1alpha1Endpoint>}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    endpoints: Array<IoK8sApiDiscoveryV1alpha1Endpoint>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    kind?: string;
    /**
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * ports specifies the list of network ports exposed by each endpoint in this slice. Each port must have a unique name. When ports is empty, it indicates that there are no defined ports. When a port is defined with a nil port value, it indicates \"all ports\". Each slice may include a maximum of 100 ports.
     * @type {Array<IoK8sApiDiscoveryV1alpha1EndpointPort>}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointSlice
     */
    ports?: Array<IoK8sApiDiscoveryV1alpha1EndpointPort>;
}
