// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TokenRequestStatus is the result of a token request.
 * @export
 * @interface IoK8sApiAuthenticationV1TokenRequestStatus
 */
export interface IoK8sApiAuthenticationV1TokenRequestStatus {
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiAuthenticationV1TokenRequestStatus
     */
    expirationTimestamp: Date;
    /**
     * Token is the opaque bearer token.
     * @type {string}
     * @memberof IoK8sApiAuthenticationV1TokenRequestStatus
     */
    token: string;
}
