// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.17.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EndpointConditions represents the current condition of an endpoint.
 * @export
 * @interface IoK8sApiDiscoveryV1alpha1EndpointConditions
 */
export interface IoK8sApiDiscoveryV1alpha1EndpointConditions {
    /**
     * ready indicates that this endpoint is prepared to receive traffic, according to whatever system is managing the endpoint. A nil value indicates an unknown state. In most cases consumers should interpret this unknown state as ready.
     * @type {boolean}
     * @memberof IoK8sApiDiscoveryV1alpha1EndpointConditions
     */
    ready?: boolean;
}
